# This is a basic workflow to help you get started with Actions

name: TEST CI/CD Step


on:
  push:
   branches: ["main"]

  workflow_dispatch:

jobs:

 build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

  - name: Demo Build
    run: echo Hello Retool && exit 1

  - name: Alerts
    if: ${{ failure() }}
    uses: twilio-labs/actions-sms@v1
    with:
      fromPhoneNumber: ${{ secrets.FROM_NUMBER }}
      toPhoneNumber: ${{ secrets.TO_NUMBER }}
      message: ${{ github.job }} job of ${{ github.repository }}
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}